import React, { useEffect, useState } from 'react';
import { Plus, Pencil, X, PackageOpen, Trash2 } from 'lucide-react';
import { api } from '../services/api';

const blank = { name: '', slug: '', price: '', sale_price: '', description: '', status: 'draft', featured: false };
const slugify = (text) => text.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export default function ProductManager() {
  const [products, setProducts] = useState([]); const [form, setForm] = useState(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.get('/admin/products').then(r => setProducts(r.data.data || [])).catch(e => setMessage(e.response?.data?.message || 'Could not load products. Please sign in as an administrator.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const update = (field, value) => setForm(current => ({ ...current, [field]: value }));
  async function save(event) { event.preventDefault(); setMessage(''); const {imageFile,...values}=form; const payload = { ...values, price: Number(form.price), sale_price: form.sale_price ? Number(form.sale_price) : null }; try { const response=form.id ? await api.put(`/admin/products/${form.id}`, payload) : await api.post('/admin/products', payload); if(imageFile){const imageData=new FormData();imageData.append('image',imageFile);imageData.append('alt_text',form.name);await api.post(`/admin/products/${response.data.id}/images`,imageData);} setForm(null); setMessage(imageFile?'Product and image saved successfully.':'Product saved successfully.'); load(); } catch (e) { setMessage(e.response?.data?.message || 'Could not save product or image.'); } }
  async function archive(product) { if (!window.confirm(`Archive “${product.name}”? It will no longer show in the shop.`)) return; try { await api.delete(`/admin/products/${product.id}`); setMessage('Product archived.'); load(); } catch (e) { setMessage(e.response?.data?.message || 'Could not archive product.'); } }
  return <div className="admin-content"><div className="admin-heading"><div><p className="eyebrow">CATALOGUE</p><h1>Products</h1></div><button className="button green" onClick={() => setForm(blank)}><Plus size={18}/> Add product</button></div>{message && <div className="admin-note">{message}</div>}{form && <form className="product-form" onSubmit={save}><div className="form-heading"><h2>{form.id ? 'Edit product' : 'New product'}</h2><button type="button" className="remove" onClick={() => setForm(null)}><X size={17}/></button></div><div className="two"><input required value={form.name} placeholder="Product name" onChange={e => { update('name', e.target.value); if (!form.id) update('slug', slugify(e.target.value)); }}/><input required value={form.slug} placeholder="product-slug" onChange={e => update('slug', slugify(e.target.value))}/></div><div className="two"><input required min="1" type="number" value={form.price} placeholder="Regular price (PKR)" onChange={e => update('price', e.target.value)}/><input min="1" type="number" value={form.sale_price || ''} placeholder="Sale price (optional)" onChange={e => update('sale_price', e.target.value)}/></div><textarea value={form.description || ''} placeholder="Product description" onChange={e => update('description', e.target.value)}/><label className="image-upload"><b>Product image</b><span>JPG, PNG, or WebP · maximum 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>update('imageFile',e.target.files?.[0]||null)}/>{form.imageFile&&<span className="selected-file">Selected: {form.imageFile.name}</span>}</label><div className="two"><select value={form.status} onChange={e => update('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><label className="check"><input type="checkbox" checked={form.featured} onChange={e => update('featured', e.target.checked)}/> Feature on homepage</label></div><button className="button green">Save product</button></form>}{loading ? <p>Loading live products…</p> : <div className="admin-table"><div className="table-row table-head"><span>Product</span><span>Status</span><span>Price</span><span>Action</span></div>{products.map(product => <div className="table-row" key={product.id}><span><b>{product.name}</b><small>{product.slug}</small></span><span><i className={`status ${product.status}`}>{product.status}</i></span><span>Rs. {Number(product.sale_price || product.price).toLocaleString()}</span><span className="row-actions"><button className="edit" onClick={() => setForm(product)}><Pencil size={16}/> Edit</button><button className="edit danger" onClick={() => archive(product)}><Trash2 size={16}/> Archive</button></span></div>)}{!products.length && <div className="empty"><PackageOpen/><p>No products have been created yet.</p></div>}</div>}</div>;
}
